apply_spatial_attention: false
betas: !!python/tuple
- 0.9
- 0.999
check_gradients: false
data_imputed: true
delta: 3.0
dim_feedforward: 128
dropout: 0.3
embed_dim: 32
features: !!python/object/apply:numpy._core.multiarray._reconstruct
  args:
  - &id001 !!python/name:numpy.ndarray ''
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 13
  - !!python/object/apply:numpy.dtype
    args:
    - U23
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - 92
    - 4
    - 8
  - false
  - !!binary |
    YQAAAHYAAABnAAAAXwAAAHMAAABhAAAAbAAAAGUAAABfAAAAdAAAAG8AAABfAAAAbAAAAGkAAABz
    AAAAdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABoAAAAbwAAAG0AAABlAAAAcwAAAF8A
    AABzAAAAbwAAAGwAAABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAGkAAABuAAAAdgAAAGUAAABuAAAAdAAAAG8AAAByAAAAeQAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbQAAAGUAAABk
    AAAAaQAAAGEAAABuAAAAXwAAAGQAAABvAAAAbQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABtAAAAZQAAAGQAAABpAAAAYQAAAG4AAABfAAAAbAAA
    AGkAAABzAAAAdAAAAF8AAABwAAAAcAAAAHMAAABmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAG0AAABlAAAAZAAAAGkAAABhAAAAbgAAAF8AAABsAAAAaQAAAHMAAAB0AAAAXwAAAHAAAABy
    AAAAaQAAAGMAAABlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbQAAAGUAAABkAAAAaQAAAGEA
    AABuAAAAXwAAAHAAAABwAAAAcwAAAGYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAABtAAAAZQAAAGQAAABpAAAAYQAAAG4AAABfAAAAcwAAAGEAAABsAAAA
    ZQAAAF8AAABwAAAAcgAAAGkAAABjAAAAZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG4AAABl
    AAAAdwAAAF8AAABsAAAAaQAAAHMAAAB0AAAAaQAAAG4AAABnAAAAcwAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbwAAAGYAAABmAAAAXwAAAG0AAABhAAAAcgAA
    AGsAAABlAAAAdAAAAF8AAABpAAAAbgAAAF8AAAB0AAAAdwAAAG8AAABfAAAAdwAAAGUAAABlAAAA
    awAAAHMAAABwAAAAZQAAAG4AAABkAAAAaQAAAG4AAABnAAAAXwAAAHMAAABhAAAAbAAAAGUAAABz
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAABlAAAAcgAAAGkA
    AABvAAAAZAAAAF8AAABkAAAAdQAAAHIAAABhAAAAdAAAAGkAAABvAAAAbgAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAcwAAAG8AAABsAAAAZAAAAF8AAABhAAAAYgAAAG8AAAB2AAAA
    ZQAAAF8AAABsAAAAaQAAAHMAAAB0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
gamma: 1.0
loss_type: huber
lr: 0.001
lr_decay: 0.3
lr_patience: 2
num_heads_decoder: 1
num_heads_encoder: 1
num_layers_decoder: 2
num_layers_encoder: 2
prediction_window:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
print_output_stats: false
property_types: !!python/object/apply:numpy._core.multiarray._reconstruct
  args:
  - *id001
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 5
  - !!python/object/apply:numpy.dtype
    args:
    - U25
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - 100
    - 4
    - 8
  - false
  - !!binary |
    QQAAAGwAAABsAAAAIAAAAFIAAABlAAAAcwAAAGkAAABkAAAAZQAAAG4AAAB0AAAAaQAAAGEAAABs
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEMAAABvAAAAbgAAAGQA
    AABvAAAALwAAAEMAAABvAAAALQAAAG8AAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABNAAAAdQAAAGwAAAB0AAAAaQAAAC0AAABGAAAA
    YQAAAG0AAABpAAAAbAAAAHkAAAAgAAAAKAAAADIAAAAtAAAANAAAACAAAABVAAAAbgAAAGkAAAB0
    AAAAKQAAAAAAAAAAAAAAUwAAAGkAAABuAAAAZwAAAGwAAABlAAAAIAAAAEYAAABhAAAAbQAAAGkA
    AABsAAAAeQAAACAAAABSAAAAZQAAAHMAAABpAAAAZAAAAGUAAABuAAAAdAAAAGkAAABhAAAAbAAA
    AFQAAABvAAAAdwAAAG4AAABoAAAAbwAAAHUAAABzAAAAZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
shift: 3.0
window_size: 36
